version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Create venv
          command: |
            virtualenv flaskops
      - run:
          name: Install python dependencies
          command: |
            . flaskops/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Linter
          command: |
            . flaskops/bin/activate
            pylint --load-plugins pylint_flask --fail-under=7 app.py
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t smirnovigor077/flask-ops:${CIRCLE_SHA1} .
      - run:
         name: Push Docker Image to DockerHub
         command: |
            docker login -u $DOCKER_LOGIN --password=$DOCKER_PWD
            docker push smirnovigor077/flask-ops:${CIRCLE_SHA1}
  tests:
    machine: true
    steps:
      - checkout
      - run:
          name: Test Image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker pull smirnovigor077/flask-ops:${CIRCLE_SHA1}
            docker run --rm -it smirnovigor077/flask-ops:${CIRCLE_SHA1} python tests.py
workflows:
  version: 2
  flask-ops-cicd:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - tests:
          requires:
            - build
