version: 2.1
jobs:
  tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Create venv
          command: |
            virtualenv flaskops
      - run:
          name: Install python dependencies
          command: |
            . flaskops/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Linter
          command: |
            . flaskops/bin/activate
            pylint --load-plugins pylint_flask --fail-under=7 app.py tests.py
      - run:
          name: Run Unit tests
          command: |
            . flaskops/bin/activate
            python tests.py
      - store_artifacts:
          path: test-reports/
          destination: tr:${CIRCLE_SHA1}
      - store_test_results:
          path: test-reports/
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build --build-arg salt=${SECRET_SALT} -t registry.heroku.com/${HEROKU_APP_NAME}/web .
      - run:
          name: Integration Tests
          command: |
            docker run --rm -it registry.heroku.com/${HEROKU_APP_NAME}/web python -m pytest -vv
      - run:
         name: Push Docker Image to Heroku Registry
         command: |
            echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
            docker push registry.heroku.com/${HEROKU_APP_NAME}/web
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            bash setup-heroku.sh
            echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
            heroku container:release web --app ${HEROKU_APP_NAME}
workflows:
  version: 2
  flask-ops-cicd:
    jobs:
      - tests
      - build:
          requires:
            - tests
      - deploy:
          requires:
            - build
