version: 2.1
jobs:
  linter:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Create venv
          command: |
            virtualenv flaskops
      - run:
          name: Install python dependencies
          command: |
            . flaskops/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Linter
          command: |
            . flaskops/bin/activate
            pylint --load-plugins pylint_flask --fail-under=7 app.py
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build --build-arg salt=${SECRET_SALT} -t registry.heroku.com/flask-ops:${CIRCLE_SHA1} .
      - run:
         name: Push Docker Image to Heroku Registry
         command: |
            echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
            docker push registry.heroku.com/flask-ops:${CIRCLE_SHA1}
  tests:
    machine: true
    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
            docker pull registry.heroku.com/flask-ops:${CIRCLE_SHA1}
            docker run --rm -it registry.heroku.com/flask-ops:${CIRCLE_SHA1} python tests.py
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

workflows:
  version: 2
  flask-ops-cicd:
    jobs:
      - linter
      - build:
          requires:
            - linter
      - tests:
          requires:
            - build
